# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ff3f994ea9e4d91b7e315fe10cd594508bd2f9eaeec9eec43fdede61f7a94fcb90963e3ab8945b9b4a238e0a1f3e96ca241d9925ebecf304b428df7aa0ddabe4

test:
  secret_key_base: 184346538e74f50a5725d45e8ae58ba85ab70c6eea5f955fe46a647dbfb36c9676910d04ee060b2e92ad400ace015a13c8ed64f22963790ebdeb038c7ad13631

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
